project:
  title: "ts-analysis"
  type: website
  output-dir: docs
  
format:
  html:
    fig-format: svg
    toc: true
    toc-location: left
    toc-depth: 2
    toc-title: "Оглавление"
    number-sections: true
    
execute:
  cache: true
  
knitr:
  opts_chunk:
    out-width: 100%
    comment: "##"